name: flutter_sqlite_demo
description: A new Flutter project using SQLite for local data storage.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Package untuk SQLite
  sqflite: ^2.4.2

  # Package untuk path database lokal
  path: ^1.8.0

  # Optional: untuk animasi & icon material
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
